# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.test import TestCase

# Create your tests here.
json_data = {
'links': [{'color': 'orange', 'source': 0, 'type': 'solid', 'target': 1},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 1},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 1},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 1},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 1},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 3},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 4},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 4},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 4},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 4},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 1},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 1},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 3},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 4},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 4},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 4},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 4},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 1},
        {'color': 'orange', 'source': 0, 'type': 'solid', 'target': 2},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 5},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 5},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 5},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 5},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 5},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 5},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 6},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 7},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 7},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 7},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 7},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 5},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 5},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 6},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 0},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 7},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 7},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 7},
        {'color': 'orange', 'source': 2, 'type': 'solid', 'target': 7},
],
'nodes': [{'image': 'taipan', 'id': 4, 'name': 'CAT6KGDL-10G_03_INTERNET'},
        {'image': 'nexus', 'id': 2, 'name': 'NEXUS9K-GDL-DATOS-2'},
        {'image': 'nexus', 'id': 0, 'name': 'NEXUS9K-GDL-DATOS-1'},
        {'image': 'router', 'id': 1, 'name': 'PE_INTERNET_ASR9K10_GDL_CTC_NEW-1'},
        {'image': 'switch', 'id': 6, 'name': 'CAT6KGDL-10G_02'},
        {'image': 'switch2', 'id': 3, 'name': 'CAT6KGDL-10G_01'},
        {'image': 'router', 'id': 5, 'name': 'PE_INTERNET_ASR9K10_GDL_CTC_NEW-2'},
        {'image': 'switch', 'id': 7, 'name': 'CAT6KGDL-10G_04_INTERNET'},
]
}
