# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-25 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_mcast_flows_host_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.CharField(max_length=200)),
                ('script_type', models.CharField(max_length=200)),
                ('file_location', models.CharField(max_length=200)),
                ('data_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
