"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.11.20.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

if os.name == 'nt':
    POSTGRES_DB = 'localhost'
else:
    POSTGRES_DB = 'mega-postgres'

#CUSTOM ROOT VARIABLES ###
## JOC VARS ###
MEDIA_ROOT = './nxos/session_logs/'
MEDIA_ROOT_XR = './xr/session_logs/'
TACACS_USER='provciscojosec'
TACACS_PASSWORD='3g:IEqupqd'
LISTA_CMD=['show clock','show running-config'
,'show spanning-tree'
,'show spanning-tree | i VLAN|root|Address'
,'show spanning-tree detail'
,'show ip interface brief'
,'show ip bgp summary'
,'show ip ospf neighbor'
,'show interface'
,'show ip route summary'
,'show ip route'
,'show ip arp'
,'show ip pim neighbor'
,'show ip pim rp'
,'show ip pim group-range'
,'show ip pim interface'
,'show ip mroute detail'
,'show ip mroute summ'
,'show forwarding multicast route'
,'show ip igmp snooping'
,'show ip igmp snooping mrouter'
,'show ip igmp snooping groups'
,'show ip igmp snooping groups detail'
,'show ip igmp groups'
,'show mac address-table'
,'show ntp peer-status'
,'show ntp session status'
,'show logging']
LISTA_CMD_XR=['show clock','show running-config'
,'show ipv4 vrf all interface brief'
,'show bgp summary'
,'show ospf neighbor'
,'show interface description'
,'show route summary'
,'show logging']
## END JOC VARS ###

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&@1j=viy#wz5o+l_o%#-(q%q(%h4i64b$m3-)*eow&kucq(e0k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

# Application definition

INSTALLED_APPS = [
    'nxos.apps.NXOSConfig',
    'xr.apps.XRConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'mega_data',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': POSTGRES_DB,
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
