# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-20 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
            ],
        ),
    ]
