# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-21 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos', '0002_mcast_flows'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcast_flows',
            name='host_id',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
