# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-28 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos', '0004_script_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic_interfaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.CharField(max_length=200)),
                ('interface_id', models.CharField(max_length=200)),
                ('input_rate', models.IntegerField()),
                ('output_rate', models.IntegerField()),
                ('data_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
