# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-28 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos', '0005_traffic_interfaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic_interfaces',
            name='input_rate',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='traffic_interfaces',
            name='output_rate',
            field=models.BigIntegerField(),
        ),
    ]
