# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-06 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos', '0006_auto_20200528_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARP_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.CharField(max_length=200)),
                ('arp_mac', models.CharField(max_length=200)),
                ('arp_ip', models.CharField(max_length=200)),
                ('arp_intf', models.CharField(max_length=200)),
                ('arp_vlan', models.CharField(max_length=200)),
                ('vlan_name', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
