# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-08 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos', '0007_arp_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGMP_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.CharField(max_length=200)),
                ('mcast_grp', models.CharField(max_length=200)),
                ('mcast_src', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('reporter_ip', models.CharField(max_length=200)),
                ('intf', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
